code_snippet/config/routes.rb
Rails.application.routes.draw do
  root "codes#index"

  # resources :codes do
  #   collection do
  #     resources :snippets, only: [:new, :create]
  #   end
  #   resources :snippets, only: [:edit, :show, :update]
  # end

  resources :snippets, only: [:new, :create, :edit, :update]

  resources :codes do
    resources :snippets, only: [:show, :destroy]
  end

  # resources :codes,

end

code_snippet/app/models/code.rb
class Code < ActiveRecord::Base
  has_many :snippets, dependent: :destroy
end

code_snippet/app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :code
end

code_snippet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

code_snippet/app/controllers/codes_controller.rb
class CodesController < ApplicationController
  def index
    @codes = Code.all
    # @snipppet = Snippet.all
  end
  def show
    @code = Code.find params[:id]
    # @snippets = Snippet.find
    # render text: params[:id]
  end

end

code_snippet/app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :find_contact, only: [:show, :edit, :update, :destroy]

  def find_contact
    @snippet = Snippet.find params[:id]
    @codes = Code.all
  end

  def new
    @snippet = Snippet.new
    @codes = Code.all
  end

  def create
    snippet_params = params.require(:snippet).permit(:code_id, :title, :work)
    @snippet = Snippet.new snippet_params
    if @snippet.save
      redirect_to root_path, notice: "account created!"
    else
      render :new
    end
  end

  def show
    # render text: params[:id]
  end

  def edit

  end

  def update
    # render text: "inside update #{params}"
    # @contact = Contact.find params[:id]
    snippet_params = params.require(:snippet).permit(:code_id, :title, :work)
    if @snippet.update(snippet_params)
      # render text: "path: #{posts_path}"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @code = Code.find params[:code_id]
    @snippet.destroy
    redirect_to code_path(@code)
  end
end

code_snippet/app/helpers/codes_helper.rb
module CodesHelper
end

code_snippet/app/helpers/snippets_helper.rb
module SnippetsHelper
end

code_snippet/app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "HOME", root_path %></li>
            <li><%= link_to "New Code Category", new_code_path %></li>
            <li><%= link_to "New Snippets", new_snippet_path %>
          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

code_snippet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeSnippet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%#= link_to "HOME", root_path %>
  <%#= link_to "NEW SNIPPETS", new_snippet_path %>

  <div class="container">
    <div class="col-md-2"></div>
    <div class="box col-md-8">
      <%= render "/layouts/nav" %>
      <%= yield %>
    </div>
    <div class="col-md-2"></div>
  </div>
</body>
</html>