supporter/config/routes.rb
Rails.application.routes.draw do
  # resources :contacts

  root "contacts#index"
  get "/contacts" => "contacts#index"
  post "/contacts" => "contacts#create"
  get "/contacts/new" => "contacts#new", as: :new_contact
  get "/contacts/:id/edit" => "contacts#edit", as: :edit_contact
  get "/contacts/:id" => "contacts#show", as: :contact
  patch "/contacts/:id" => "contacts#update"
  delete "/contacts/:id" => "contacts#destroy"

  # UPDATE STATUS ROUTES
  # get "/comments" => "comments#index"
  get "/contacts/:id/status" => "contacts#status", as: :edit_status

  #SEARCH ROUTES
  # resources :search
  get "/search" => "search#index"
  # get "/search/:id" => "search#result", as: :search
  post "/search" => "search#index"

  # posts_path	GET	/posts(.:format)	posts#index
  # POST	/posts(.:format)	posts#create
  # new_post_path	GET	/posts/new(.:format)	posts#new
  # edit_post_path	GET	/posts/:id/edit(.:format)	posts#edit
  # post_path	GET	/posts/:id(.:format)	posts#show
  # PATCH	/posts/:id(.:format)	posts#update
  # DELETE	/posts/:id(.:format)	posts#destroy

  # get "/posts" => "posts#index"
  # post "/posts" => "posts#create"
  # get "/posts/new" => "posts#new", as: :new_post
  # get "/posts/:id/edit" => "posts#edit", as: :edit_post
  # get "/posts/:id" => "posts#show", as: :post
  # patch "/posts/:id" => "posts#update"
  # delete "/posts/:id" => "posts#destroy"

end

supporter/app/models/contact.rb
class Contact < ActiveRecord::Base
  validates(:name, {presence: true,
                    uniqueness: true})

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: VALID_EMAIL_REGEX

  DEPARTMENT_SALES = "Sales"
  DEPARTMENT_MARKETING = "Marketing"
  DEPARTMENT_TECHNICAL = "Technical"
  DEPARTMENTS = [DEPARTMENT_SALES, DEPARTMENT_MARKETING, DEPARTMENT_TECHNICAL]

  after_initialize :set_default_values

  # def self.words_limit(limit)
  #   string_arr = self.split(' ')
  #   string_arr.count > limit ? "#{string_arr[0..(limit-1)].join(' ')}..." : self
  # end

  private

  def set_default_values
    # set the value to 5 if the value is nill
    self.status ||= 0
  end


end

supporter/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: [:show, :edit, :update, :destroy]
  ## ------
  def find_contact
    @contact = Contact.find params[:id]
  end
  def contact_params
    contact_params = params.require(:contact).permit([:name, :email, :deparment, :message, :status])
  end
  ## ------

  def index
    # render text: "index page"
    # @contact = Contact.all.order("status DESC")

    # pagination
    @page = 0
    @num = 0
    @page = params[:page] if params.has_key?(:page)
    if (@page!=0)
      @num = (@page.to_i - 1) * 10
    end
    # @contact = Contact.paginate(:page => @page, :per_page => 5).order("created_at DESC")
    @contact = Contact.order("status DESC").page(params[:page]).per(10)
    # @contact = Contact.order("name").page(params[:page]).per(5)
    # @users = User.order(:name).page params[:page]

  end
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
        redirect_to(contacts_path)
    else
        render :new
    end
  end
  def show
    # @contact = Contact.find(params[:id])
  end
  def edit
    # @contact = Contact.find(params[:id])
  end
  def update
    # render text: "inside update #{params}"
    # @contact = Contact.find params[:id]
    if @contact.update(contact_params)
      # render text: "path: #{posts_path}"
      redirect_to contacts_path
    else
      render :edit
    end
  end
  def destroy
    # @contact = Post.find params[:id]
    @contact.destroy
    redirect_to contacts_path
  end

  def status
    @status = Contact.find params[:id]
    if @status.status == 0
      status = 1
    else
      status = 0
    end
    if @status.update({status: status})
      # render text: "status updated!!"
      redirect_to contacts_path
    else
      render text: "status not updated!!"
    end
    # render text: "inside update #{params[:id]}<br>current status: #{@status.status}<br>change to: #{status}"

    # q.update({view_count:100, title: "hello world"})
  end

  def search_term
    # search_params = params.permit([:search])
    # @search = search_params[:search]
    # render text: "inside search #{params[:id]}<br>current status: #{@status.status}<br>change to: #{status}"
    # @contact = Contact.where(["name ilike :search_term OR
    #   email ilike :search_term OR
    #   message ilike :search_term", {search_term: "%#{@search}%"}]).order("created_at DESC")
  end

end

supporter/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    search_params = params.permit([:search])
    @search = search_params[:search]
    # render text: "inside search #{params}<br>search: #{@search}"
    # render text: "inside search #{params[:id]}<br>current status: #{@status.status}<br>change to: #{status}"
    @contact = Contact.where(["name ilike :search_term OR
      email ilike :search_term OR
      message ilike :search_term", {search_term: "%#{@search}%"}]).order("created_at DESC")
  end
end

supporter/app/views/contacts/_form.html.erb
<div class="well">

  <% if !@contact.errors.empty? %>
    <div class="red-sm">Error (s) :
      <%= @contact.errors.full_messages.join(", ") %> !!
    </div>
  <% end %>
  <%= form_for @contact do |f| %>
    <div class="form-group">
      <%= f.label :name, class: "control-label text-right" %>
      <%= f.text_field :name, class: "form-control", placeholder: "full name" %>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "control-label text-right" %>
      <%= f.text_field :email, class: "form-control", placeholder: "eg. justin@codecore.ca" %>
    </div>
    <div class="form-group">
      <%= f.label :department, class: "control-label text-right" %>:<br>

      <%= f.radio_button("deparment", "Sales") %>
      <%= f.label :deparment, "Sales", :value => "Sales", class: "control-label text-right" %>
      &nbsp;&nbsp;
      <%= f.radio_button("deparment", "Marketing") %>
      <%= f.label :deparment, "Marketing", :value => "Marketing", class: "control-label text-right" %>
      &nbsp;&nbsp;
      <%= f.radio_button("deparment", "Technical") %>
      <%= f.label :deparment, "Technical", :value => "Technical", class: "control-label text-right" %>
    </div>
    <div class="form-group">
      <%= f.label :message, class: "control-label text-right"  %>
      <%= f.text_area :message, class: "form-control", placeholder: "message ..", rows: "4"%>
    </div>
    <div class="form-group">
        <%= f.submit(class: "btn btn-primary") %>
        <%= link_to 'Cancel', contacts_path, class:"btn btn-primary" %>
    </div>
  <% end %>

</div>

supporter/app/views/contacts/edit.html.erb
<h3 class="blog-sub-title text-center">edit a contact</h3>

<%= render "form" %>

supporter/app/views/contacts/index.html.erb
<div>
  <!-- <div class="site-head-line text-center margin-top-30"></div> -->
  <div class="margin-top-30">
    <% if @search %>
    <div><h4>Search for keyword(s) : <%= @search %></h4></div>
    <% end %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Email</th>
          <th>Department</th>
          <th>Message</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @contact.each do |p| %>
        <% @num += 1 %>
        <tr><td><%= @num %></td>
            <td><%= p.name %></td>
            <td><%= mail_to p.email %></td>
            <td><%= p.deparment %></td>
            <td><%= p.message.split.first(5).join(' ') %> ...</td>
            <!-- <td><%#= Contact.words_limit(p.message, 5) %> ...</td> -->
            <td width="115"><%= link_to "", edit_contact_path(p), class: "glyphicon glyphicon-edit" %>
                <%= link_to "", contact_path(p), class: "glyphicon glyphicon-trash",
                            method: :delete,
                            data: {confirm: "Are you sure to delete?"} %>
                <% if p.status == 0 %>
                  <%= link_to 'Not done', edit_status_path(p.id), class:"btn btn-default btn-xs" %>
                <% else %>
                  <%= link_to 'Done', edit_status_path(p.id), class:"btn btn-default btn-xs",
                    data: {confirm: "Current status is Done. \n Are you sure to change this status?"} %>
                <% end %>
            </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <!-- <div>Number of records: <%#= @contact.length %></div> -->
  </div>
  <div class="text-center">
    <%= paginate @contact %>
  </div>
</div>

supporter/app/views/contacts/new.html.erb
<h3 class="blog-sub-title text-center">create a new contact</h3>
  <%= render "form" %>

supporter/app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Supporter System", root_path, class: "navbar-brand lobster" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "HOME", root_path %></li>
<!--
            <li><%#= link_to "About", about_path %></li>
            <li><%#= link_to "Blog", blogs_path %>
 -->
          </ul>
          <!-- #search navbar -->
          <%= form_tag search_path, class: "navbar-form navbar-left", role: "search" do %>
            <div class="form-group">
              <%= text_field_tag(:search, nil, class: "form-control", placeholder: "search contact ...") %>
            </div>
            <%= submit_tag("search", class: "btn btn-default") %>
          <% end %>
          <!-- # -->
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><%= link_to 'Create a new contact', new_contact_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

supporter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Support Requests</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "/layouts/nav" %>
  <%# if !current_page?(root_path) %>
    <div class="container">
      <div class="col-md-1"></div>
      <div class="box col-md-10">
          <h1 class="blog-title text-center lobster">Supporter System</h1>
          <%= yield %>
      </div>
      <div class="col-md-1"></div>
    </div>
  <%# end %>
</body>
</html>

supporter/app/views/search/index.html.erb
<div>
  <!-- <div class="site-head-line text-center margin-top-30"></div> -->
  <div class="margin-top-30">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Email</th>
          <th>Department</th>
          <th>Message</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% num = 0 %>
        <% @contact.each do |p| %>
        <% num += 1 %>
        <tr><td><%= num %></td>
            <td><%= p.name %></td>
            <td><%= mail_to p.email %></td>
            <td><%= p.deparment %></td>
            <td><%= p.message.split.first(5).join(' ') %> ...</td>
            <td><%= link_to "", edit_contact_path(p), class: "glyphicon glyphicon-edit" %>
                <%= link_to "", contact_path(p), class: "glyphicon glyphicon-trash",
                            method: :delete,
                            data: {confirm: "Are you sure to delete?"} %>
                <% if p.status == 0 %>
                  <%= link_to 'Not done', edit_status_path(p.id), class:"btn btn-default btn-xs" %>
                <% else %>
                  <%= link_to 'Done', edit_status_path(p.id), class:"btn btn-default btn-xs",
                    data: {confirm: "Current status is Done. \n Are you sure to change this status?"} %>
                <% end %>
            </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>