blog/config/routes.rb
Rails.application.routes.draw do
  # resources :posts

  root "home#index"
  get "/" => "home#index"
  get "/about" => "home#about"

  resources :users, only: [:new, :create]

  resources :blogs, only: [:index, :show] do
    resources :comments
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  # resources :codes do
  #   resources :snippets, only: [:show, :destroy]
  # end

  # get "/blogs" => "home#blogs"
  # get "/blogs/:id" => "home#view", as: :view_blog

  #POST ROUTES
  resources :posts
  # get "/posts" => "posts#index"
  # post "/posts" => "posts#create"
  # get "/posts/new" => "posts#new", as: :new_post
  # get "/posts/:id/edit" => "posts#edit", as: :edit_post
  # get "/posts/:id" => "posts#show", as: :post
  # patch "/posts/:id" => "posts#update"
  # delete "/posts/:id" => "posts#destroy"

  #COMMENT ROUTES
  resources :comments, only: [:index, :create]
  # get "/comments" => "comments#index"
  # post "/comments" => "comments#create"

  #SEARCH ROUTES
  # resources :search
  get "/search" => "search#index"
  # get "/search/:id" => "search#result", as: :search
  post "/search" => "search#index"

end

blog/app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "the sound of life", root_path, class: "navbar-brand lobster" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "HOME", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Blog", blogs_path %>
          </ul>
          <!-- #search navbar -->
          <%= form_tag search_path, class: "navbar-form navbar-left", role: "search" do %>
            <div class="form-group">
              <%= text_field_tag(:search, nil, class: "form-control", placeholder: "search blog ...") %>
            </div>
            <%= submit_tag("search", class: "btn btn-default") %>
          <% end %>
          <!-- # -->

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="active"><a href="#">Log in as <%= current_user.first_name %></a></li>
              <li><%= link_to "Log Out", sessions_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", new_session_path %></li>
              <!-- <li><%#= link_to "Sign Up", new_user_path %></li> -->
            <% end %>

            <% if @post %>
              <li class="active"><%= link_to 'Create a new post', new_post_path %></li>
            <% else %>
              <li><%= link_to 'Blog Control Panel', posts_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mini Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "/layouts/nav" %>
  <% if !current_page?(root_path) %>
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:alert] %></div>
    <% end %>

    <!-- <div class="ratio" style="background-image:url('http://4.bp.blogspot.com/-Z9r-RBHSms8/VhEQ2tbTysI/AAAAAAAAAck/NgYkenDHyLQ/s1600/photo-1423753623104-718aaace6772.jpg')" /> -->

      <div class="container ratio" style="background-image:url('https://c2.staticflickr.com/8/7564/15865514029_d72333328c_h.jpg')">
        <div class="col-md-2"></div>
        <div class="col-md-2"></div>
        <div class="box col-md-8 blog-border" style="background-color: rgba(250, 250, 250, .7); height: 600px; overflow: scroll;">
          <% if @post %>
            <h1 class="blog-title text-center lobster">Blog's Control Panel</h1>
          <% end %>
          <%= yield %>
        </div>
      </div>
  <% else %>
    <%= yield %>
  <% end %>
</body>
</html>