idea_factory/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root "ideas#index"
  resources :users, except: [:show, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :ideas do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :joins, only: [:create, :destroy]
  end

end

idea_factory/app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user

  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  has_many :joins, dependent: :destroy
  has_many :joins_users, through: :joins, source: :user

  # ----------------------------------------------------------------------------

  after_initialize :set_default_values
  before_validation :capitalize_title

  validates :title, presence: true,
                    uniqueness: {message: "was already used"},
                    length:    {minimum: 3}
  validates :body, presence: true,
                  uniqueness: {scope: :title}

  validates :view_count, numericality: {greater_than_or_equal_to: 0}

  # ----------------------------------------------------------------------------

  def liked_by?(user)
    like_for(user).present?
  end

  def like_for(user)
    likes.find_by_user_id(user.id)
  end

  def joined_by?(user)
    join_for(user).present?
  end

  def join_for(user)
    joins.find_by_user_id(user.id)
  end


  private

    def set_default_values
      self.view_count ||= 0
    end

    def capitalize_title
      self.title.capitalize! if title
    end

end

idea_factory/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]
  # before_action :authorize, only: [:edit, :update, :destroy]
  before_action :idea, only: [:show, :edit, :update, :destroy]


  def index
    @page = 0
    @num = 0
    @page = params[:page] if params.has_key?(:page)
    if (@page!=0)
      @num = (@page.to_i - 1) * 10
    end
    @ideas = Idea.all.order("id DESC").page(params[:page]).per(10)
  end

  def new
    @ideas = Idea.new
  end

  def create
    @ideas = Idea.new(idea_params)
    @ideas.user = current_user
    if @ideas.save
      redirect_to(root_path, notice: "Question created!")
    else
      flash.now[:alert] = 'Error while sending message!'
      render :new
    end
  end

  def show
    # if (current_user.nil?)
    #   @ideas.view_count += 1
    #   @ideas.save
    # elsif (@ideas.user.displayname != current_user.displayname)
    #   @ideas.view_count += 1
    #   @ideas.save
    # end
    @comment = Comment.new
    @join_member = idea.joins.map(&:user_id)
    @join_member.push idea.user_id
    @join_member = User.where(id: [@join_member])
  end
  def edit
    redirect_to root_path, alert: "Access denied." unless can? :edit, @ideas
  end
  def update
    if @ideas.update(idea_params)
      redirect_to idea_path(@ideas), notice: "Idea updated!"
    else
      render :edit
    end
  end
  def destroy
    @ideas.destroy
    flash[:notice] = "Idea deleted successfully"
    redirect_to ideas_path
  end

  def idea
    @ideas ||= Idea.find params[:id]
  end
  def idea_params
    params.require(:idea).permit([:title, :body])
  end


end

idea_factory/app/helpers/ideas_helper.rb
module IdeasHelper
end

idea_factory/app/views/ideas/_form.html.erb
  <% if !@ideas.errors.empty? %>
    <div class="red-sm">Error (s) :
      <%= @ideas.errors.full_messages.join(", ") %> !!
    </div>
  <% end %>

  <%= form_for @ideas do |f| %>
    <div class="form-group">
      <%= f.label :title, class: "control-label text-right" %>
      <%= f.text_field :title, class: "form-control", placeholder: "title" %>
    </div>
    <div class="form-group">
      <%= f.label :body, class: "control-label text-right"  %>
      <%= f.cktext_area :body, class: "form-control", :cols => 40, :ckeditor => {:toolbar => 'MyToolbar'} %>
      <%#= f.text_area :body, class: "form-control", placeholder: "input question ..", rows: "4"%>
    </div>
    <div class="form-group">
        <%= f.submit(class: "btn btn-primary") %>
        <%= link_to 'Cancel', ideas_path, class:"btn btn-primary" %>
    </div>
  <% end %>

idea_factory/app/views/ideas/edit.html.erb
<div class="col-md-10 col-md-offset-1 top-50">
  <h1 class="oswald font-37">EDIT YOUR IDEA</h1>
    <div class="form-wall">
      <%= render "form" %>
    </div>
</div>

idea_factory/app/views/ideas/index.html.erb
<h1 class="oswald font-37">Idea Factory</h1>
<hr>
<% @ideas.each do |idea| %>
    <div class="col-md-12">
        <span class="font-16"><strong><%= link_to idea.title, idea_path(idea) %></strong></span>
        <p><%= ActionView::Base.full_sanitizer.sanitize(idea.body).html_safe %></p>
    </div>
    <div class="col-md-4 color-77">
      <i class="glyphicon glyphicon-time"></i> <%= time_ago_in_words(idea.created_at) %> ago<br>
      <i class="glyphicon glyphicon-user"></i> <%= idea.user.displayname %> <br>
    </div>
    <% if !(idea.user == current_user) %>
      <div class="col-md-4">

        <!-- JOIN BUTTON -->
        <% if user_signed_in? && idea.joined_by?(current_user) %>
          <%= link_to "JOINED", idea_join_path(idea, idea.join_for(current_user)), class: "btn btn-primary", method: :delete %>
        <% else %>
          <%= link_to "JOIN", idea_joins_path(idea), class: "btn btn-default", method: :post %>
        <% end %>

        <!-- LIKE BUTTON -->
        <% if user_signed_in? && idea.liked_by?(current_user) %>
          <%= link_to "LIKED", idea_like_path(idea, idea.like_for(current_user)), class: "btn btn-primary", method: :delete %>
        <% else %>
          <%= link_to "LIKE", idea_likes_path(idea), class: "btn btn-default", method: :post %>
        <% end %>

      </div>
    <% else %>
      <div class="col-md-4">&nbsp;</div>
    <% end %>
    <div class="col-md-4 text-right">
      <span>Members: <%= idea.joins.count %></span> |
      <span>Likes: <%= idea.likes.count %></span>
    </div>
    <div class="col-md-12">
      <hr>
    </div>
<% end %>
<div class="text-center">
  <%#= paginate @q %>
</div>

idea_factory/app/views/ideas/new.html.erb
<div class="col-md-10 col-md-offset-1 top-50">
  <h1 class="oswald font-37">CREATE NEW IDEA</h1>
    <div class="form-wall">
      <%= render "form" %>
    </div>
</div>

idea_factory/app/views/ideas/show.html.erb
<div class="top-50"></div>
<h2><%= @ideas.title %></h2>

<hr>

  <div>
    <% if !(can? :manage, @ideas) %>
    <div class="col-md-1 text-center">
      <%# Join Idea ------------------------------------------------------------------------ %>
      <% if user_signed_in? && @ideas.joined_by?(current_user) %>
        <%= link_to "\nJOINED", idea_join_path(@ideas, @ideas.join_for(current_user)), class: "glyphicon glyphicon-ok-sign font-16 text-danger", method: :delete %>
      <% else %>
        <%= link_to "\nJOIN?", idea_joins_path(@ideas), class: "glyphicon glyphicon-ok-circle font-16 text-info", method: :post %>
      <% end %>
      <br><br>
      <%# Like Idea ------------------------------------------------------------------------ %>
      <% if user_signed_in? && @ideas.liked_by?(current_user) %>
        <%= link_to "\nLIKED", idea_like_path(@ideas, @ideas.like_for(current_user)), class: "glyphicon glyphicon-heart font-16 text-info", method: :delete %>
      <% else %>
        <%= link_to "\nLIKE", idea_likes_path(@ideas), class: "glyphicon glyphicon-heart-empty font-16 text-info", method: :post %>
      <% end %>
      <%# ---------------------------------------------------------------------------------- %>

    </div>
    <div class="col-md-9 opensans font-16"><p><%= @ideas.body.html_safe %></p></div>
    <% else %>
    <div class="col-md-10 opensans font-16"><p><%= @ideas.body.html_safe %></p></div>
    <% end %>
    <div class="col-md-2 opensans font-12 reset-margin">
      <div class="well">
        Created by: <%= @ideas.user.displayname %><br>
        <%= time_ago_in_words(@ideas.created_at) %> ago<br>
        Viewed: <%= @ideas.view_count %>
      </div>
      <% if (can? :manage, @ideas) %>
      <div class="well text-center">
        <span class="text-center">
          <% if can? :edit, @ideas %>
            <%= link_to "Edit", edit_idea_path(@ideas) %> |
          <% end %>
          <% if can? :destroy, @ideas %>
            <%= link_to "Delete", idea_path(@ideas),
                        method: :delete,
                        data: {confirm: "Are you sure?"} %>
          <% end %>
        Idea</span>
      </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-12">
    <hr>
    <span class="font-16 oswald">Members: <%= @join_member.map(&:displayname).join(", ") %><%#= @ideas.joins.inspect %><%#= @ideas.categories.map(&:name).join(", ") %></span>
    <hr>
  </div>

  <%# COMMENTS ----------------------------------------------------------------- %>

  <div class="col-md-12">

    <h4><%= pluralize(@ideas.comments.count, "Comment") %></h4>
    <hr>
    <% if @ideas.comments.present? %>
      <% @ideas.comments.each do |comment| %>
        <div class="col-md-12">

          <div class="col-md-2 right-border">
            <i class="glyphicon glyphicon-user"></i> <%= comment.user.displayname %><br>
            <i class="glyphicon glyphicon-time"></i> <%= time_ago_in_words(comment.created_at) %> ago
            <br>
            <%#= can? :destroy, comment %>
            <% if can? :destroy, comment %>
              <%= link_to "Delete", idea_comment_path(@ideas, comment), method: :delete,
                          class: "btn btn-danger btn-sm", data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>

          <div class="col-md-10">
              <%= comment.body.html_safe %>
          </div>

        </div>
        <div class="col-md-12">
          <hr>
        </div>
      <% end %>
    <% else %>
      <p>No comment at this moment. Be the first to comment this question by submit your comment below</p>
      <hr>
    <% end %>

    <% # --------- only signin and joined user could comment %>
    <% if user_signed_in? && @ideas.joined_by?(current_user) %>
      <div class="col-md-12">
        <% if @comment.errors.any? %>
          <%= @comment.errors.full_messages.join(", ") %>
        <% end %>

        <%= form_for [@ideas, @comment] do |f| %>
          <div class="form-group">
            <%= f.label :body, value: "Your comment" %>
            <%#= f.text_area :body, class: "form-control", rows: "8" %>
            <%= f.cktext_area :body, class: "form-control", :cols => 30, :ckeditor => {:toolbar => 'MyToolbar'} %>
          </div>
          <%= f.submit class: "btn btn-primary", value: "Post Your Comment" %>
        <% end %>

        <hr>
      </div>
    <% else %>
      <div class="col-md-12">
        Please click join above to comment
      </div>
    <% end %>



  </div>